### ISSUE TITLE
Data loss on suspend

### ISSUE THREAD

**Issue by TheSunCat** [smartfrigde/armcord#546] opened 2024-01-28 18:34 UTC
**Describe the bug**
Sometimes, when I suspend my laptop (put it to sleep), Armcord goes to this screen:
![image](https://github.com/ArmCord/ArmCord/assets/44881120/db26f431-7ed9-4213-a89b-d17cd18c8a6e)
The loading spinner animates indefinitely. I can reload to get the screen to go away.
Sometimes, after reloading, I am signed out of one or both of my Discord accounts. The option for desktop notifications is also sometimes turned off after this happening. Sometimes it also does not load Vencord.

**To Reproduce**
1. Suspend your session while Armcord is open

**Expected behavior**
Armcord should not lose state.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Method of installation: AUR
 - Version: 3.2.5-4
"About Armcord" menu option shows this: 
![image](https://github.com/ArmCord/ArmCord/assets/44881120/e64e715a-2082-47d1-a31e-e4560d437ca1)

**Additional context**
I run Armcord with this command to avoid an electron bug that causes it to keep my dGPU on at all times:
```
firejail --noprofile --blacklist=/dev/dri/card1 --blacklist=/dev/dri/renderD128 -- bash armcord --disable-smooth-scrolling --enable-features=UseOzonePlatform --ozone-platform=wayland --force_low_power_gpu --renderer-process-limit=1 --num-raster-threads=1 --no-sandbox
```

**Comment by smartfrigde** [comment] 2024-01-28 18:37
Duplicate of https://github.com/ArmCord/ArmCord/issues/545

**Closed as not planned by smartfrigde** 2024-01-28 18:37 UTC
Labels: bug
