### ISSUE TITLE
There is no titlebar

### ISSUE THREAD

**Issue by NGSpace** [smartfrigde/armcord#710] opened 2024-09-02 17:23 UTC
**Describe the bug**
Exactly as the title says, there is no titlebar.

**To Reproduce**
1. open armcord.

**Expected behavior**
There needs to be a title bar.

**Screenshots**

https://github.com/user-attachments/assets/57921c12-0fc0-491e-a812-863884bf1dd0

**Desktop (please complete the following information):**
 - OS: Linux
 - Method of installation Flatpak
 - Version 3.3.0

**Additional context**
I haven't used it for like a week, I also had trouble with my GPU drivers but I reinstalled them and everything seems to work fine (including hw acceleration) so I don't think the issue is with my compooter.

**Comment by Cyborgnetical** [comment] 2024-09-02 23:24
having same issue on fedora 40, No title bar. Attempted both flatpak and rpm installations but same issue. Can't be #700 because I have a 16 gibs of ram

**Comment by Underwaterbob** [comment] 2024-09-03 00:56
I have the same issue. Linux Mint 23.1 Cinnamon. I have to resize it across the screen to move it. Haha!

**Comment by Cyborgnetical** [comment] 2024-09-03 02:42
unrelated issue, the flatpak crashes at the end of setup, aside from that everything is still the same.

**Comment by archlyn** [comment] 2024-09-04 01:22
Having same issue on Linux Mint Cinnamon 22.  Reverting to version 3.2.8 resolved issue but obviously would like to have the title bar in newer versions.  If it matters, I have the problem with the Flatpak and the .deb in the repos

**Comment by Harsh-Noise** [comment] 2024-09-04 18:07
Fresh install of ArmCord 3.3.0 via FlatPak has no titlebar for me either. I tried installing 3.2.8 via RPM to see if it worked, but I was prevented from logging in by infinite captchas. Maybe too many logins into various 3rd party clients.
-Fedora 40 
-Gnome 
-Nvidia 3060
-16 gb ram

**Comment by smartfrigde** [comment] 2024-09-04 18:54
Duplicate of
https://github.com/ArmCord/ArmCord/issues/700

**Closed as not planned by smartfrigde** 2024-09-04 18:54 UTC
Labels: bug
