### ISSUE TITLE
ArmCord settings do not open or open in blank window

### ISSUE THREAD

**Issue by dataprolet** [smartfrigde/armcord#512] opened 2023-11-17 11:18 UTC
**Describe the bug**
Opening the ArmCord settings opens a blank window or doesn't open at all.

**To Reproduce**
1. Click on the cogwheel to open settings
2. Click on 'ArmCord Settings' -> nothing happens
3. Click on the ArmCord Version at the bottom
4. A blank window opens

**Expected behavior**
ArmCord settings should open at all or show the windows content.

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/48024821/ad83be6d-de80-4d69-bac3-76462b6fb9b5)

**Desktop (please complete the following information):**
 - OS: Arch Linux (6.6.1-zen1-1.1-zen) & KDE Plasma 5.27.9
 - AUR (armcord-bin)
 - v3.2.5-2

**Additional context**
Stable 245648 (758ffd2)
Vencord 96126fa (Web)
Electron 25.9.4
Chromium 114
Linux 64-Bit
ArmCord Version: 3.3.0

**Comment by ahydronous** [comment] 2023-12-18 18:38
Possibly related: I am not seeing any ArmCord version or access to settings in the Discord Settings menu at all.

ArmCoird 3.2.5 from Flathub:
![image](https://github.com/ArmCord/ArmCord/assets/57762816/5b8b5feb-8746-4172-a74e-8cdce88b13e0)

Vencord loading / injection is working just fine, so I'm not sure what the issue is..

**Comment by HerXayah** [comment] 2024-01-01 14:31
> Possibly related: I am not seeing any ArmCord version or access to settings in the Discord Settings menu at all.
> 
> ArmCoird 3.2.5 from Flathub: ![image](https://private-user-images.githubusercontent.com/57762816/291377170-5b8b5feb-8746-4172-a74e-8cdce88b13e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMTk3MDQsIm5iZiI6MTcwNDExOTQwNCwicGF0aCI6Ii81Nzc2MjgxNi8yOTEzNzcxNzAtNWI4YjVmZWItODc0Ni00MTcyLWE3NGUtOGNkY2U4OGIxM2UwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDE0MzAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkYTM4MGJiZDY5MzZhZWM4ZWYxODA1YzNiZGU0MTA5NDkzMDNmNTUzMDgyM2Y1NDNlYTVhZGQ4NmE1OWIwYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qORs2e-zEU75TkvSovfemkMOSLkqV_3EQbGgGKnlze4)
> 
> Vencord loading / injection is working just fine, so I'm not sure what the issue is..

Dito.
Running arch and freshly installed Armcord (3.2.5-2 in AUR) with Vencord.
![image](https://github.com/ArmCord/ArmCord/assets/45071533/dba1a41e-acbc-424e-a5b0-aa09585c5908)

**Comment by ghost** [comment] 2024-01-09 18:19
Hello, could you please provide a log file by launching the application from your terminal emulator?

P.S.
Please see https://github.com/ArmCord/ArmCord/issues/513 (also, try to remove `window.json` if it's already empty).

**Comment by smartfrigde** [comment] 2024-01-28 18:29
Fixed in 3.2.6

**Closed as completed by smartfrigde** 2024-01-28 18:29 UTC
Labels: bug
