### ISSUE TITLE
Vesktop plugins aren't available on Legcord

### ISSUE THREAD

**Issue by theoparis** [smartfrigde/armcord#753] opened 2024-10-19 00:04 UTC
![image](https://github.com/user-attachments/assets/05e00a30-4579-4d28-b9d1-929da79bbd75)

I am using the rpm package for Legcord and some plugins like Shiki Codeblocks aren't supported for some reason... Can this be fixed as this is a desktop app and not a browser extension? 🤔

**Comment by SomeAspy** [comment] 2024-10-19 16:39
duplicate of #713

**Closed as not planned by SomeAspy** 2024-10-19 16:39 UTC
