### ISSUE TITLE
Opening Armcord shows a bugged first screen

### ISSUE THREAD

**Issue by notbasetwo** [smartfrigde/armcord#568] opened 2024-04-25 18:02 UTC
**Describe the bug**
When opening Armcord on a new Chromebook, it won't display anything useful on the first screen.

**To Reproduce**
Open the application

**Expected behavior**
Application should show some form of setup/login screen. 

**Screenshots**
![Screenshot 2024-04-25 18 53 05](https://github.com/ArmCord/ArmCord/assets/71050321/08a93212-912c-4307-95a1-80f4cf2629eb)

**Desktop (please complete the following information):**
 - OS: Linux (Debian/ChromeOS Linux VM)
 - System: Mediatek Kompanio 520

**Additional context**
I ran 'armcord' in the command line and recieved some of the following errors:

https://gist.github.com/notbasetwo/cc9eb166eebf0b9d3a24f1b39fc78d44

**Comment by SomeAspy** [comment] 2024-06-10 01:05
Duplicate of #479

**Closed as not planned** 2024-06-15 09:48 UTC
Labels: bug
