### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by ghost** [smartfrigde/armcord#265] opened 2022-11-22 23:03 UTC
hi there,

is flatpak planned or considered?

**Comment by AlfredOhNO** [comment] 2022-11-22 23:12
There's an AppImage and a tarballed binary... Do you need specifically a Flatpak for some reason?

**Comment by smartfrigde** [comment] 2022-11-22 23:17
Duplicate of #122

**Closed as not planned** 2022-11-22 23:17 UTC

**Comment by orowith2os** [comment] 2022-12-04 03:21
> There's an AppImage and a tarballed binary... Do you need specifically a Flatpak for some reason?

I'd like to mention that a flatpak is useful for nontraditional systems, such as NixOS, Silverblue, and an AppImage and tarball can be a bit weird in terms of desktop integration.
