### ISSUE TITLE
Armcord crashing on Fedora 38: Gnome 44.5

### ISSUE THREAD

**Issue by pog5** [smartfrigde/armcord#468] opened 2023-09-22 05:24 UTC
**Describe the bug**
When launching ArmCord, after a bit of waiting (3-8 seconds) the app goes all white if it's in the foreground or just freezes if it's in the background.

**To Reproduce**
1. Install ArmCord (Flathub or RPM, does not matter)
2. Launch ArmCord
3. Wait a few seconds

**Log: https://pastes.dev/lhSfBgX8Mp**

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/62222436/d73bf838-5073-4323-a6cb-36af6a452b8b)
![image](https://github.com/ArmCord/ArmCord/assets/62222436/fd8091f4-5f4b-4962-b570-c417307d568b)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 38 (Workstation Edition) x86_64
 - Kernel: 6.4.15-200.fc38.x86_64
 - Method of installation flatpak (from flathub), rpm (from armcord.xyz)
 - Version 3.2.4

**Comment by pog5** [comment] 2023-09-22 05:58
Issue was unrelated to wayland as the same happens on x11

**Comment by luyu-wu** [comment] 2023-09-22 22:13
Same is happening on Arch for me.
Kernel 6.5.2 or smth.

**Comment by DarkReaperBoy** [comment] 2023-09-23 08:07
same
![image](https://github.com/ArmCord/ArmCord/assets/110972562/bf01a280-440e-49fc-904e-71900facc9a2)

**Comment by luyu-wu** [comment] 2023-09-23 15:32
Note that the fix is just uninstall (and remove app data), then reinstalling.

**Comment by smartfrigde** [comment] 2023-09-23 16:03
Duplicate of https://github.com/ArmCord/ArmCord/issues/454
Please check for solution there

**Closed as not planned by smartfrigde** 2023-09-23 16:03 UTC
Labels: bug
