### ISSUE TITLE
 socket ponged

### ISSUE THREAD

**Issue by 418teapot2** [smartfrigde/armcord#335] opened 2023-01-21 18:09 UTC
arch linux x86
linux kernel 6.16 (arch1-3)
problem: after 5 hours or so armcord's window goes white and stops working
when i try to close armcord and open it again it tells me the socket is ponged and doesnt start

i3, lightdm, X11

**Comment by smartfrigde** [comment] 2023-01-24 09:32
@418teapot2 have you been at least once in a voice call during these 5 hours?

**Comment by 418teapot2** [comment] 2023-01-28 01:00
> 

yes i am in a voice call the whole time

**Comment by smartfrigde** [comment] 2023-01-31 19:59
duplicate of #318

**Closed as not planned by smartfrigde** 2023-01-31 19:59 UTC
Labels: bug
