### ISSUE TITLE
GUI Issue - Wayland

### ISSUE THREAD

**Issue by NextWork123** [smartfrigde/armcord#336] opened 2023-01-22 18:39 UTC
**Describe the bug**
I compiled Armcord with the patches of #327 and now I am experiencing a solid color screen and am unable to do anything. I tried to start Armcord with USE_WAYLAND=0 but it seems fine, but when I click the screen sharing button, it crashes.

**Screenshots**
![Screenshot_13](https://user-images.githubusercontent.com/46625863/213933615-81ed4825-9a14-4efd-9c8c-bab271f69b8c.png)

**Desktop (please complete the following information):**
 - OS: CachyOS (Arch Linux Distro Based)
 - Method of installation: AUR
 - Version:3.2.0

**Comment by ptr1337** [comment] 2023-01-24 18:50
@orowith2os @Vendicated 

Please revert commit https://github.com/ArmCord/ArmCord/commit/a66f477af6f527d3aef3a153aa394ba56e20bce4

It is completly breaking armcord. I faced the same issue as above.

**Comment by ghost** [comment] 2023-01-25 16:09
this is exclusive to #327 because of the change to appendSwitches I guess (I did some testing)
otherwise the PR seems to be ok
but since it is merged it can't be reopened I'm pretty sure, so a new one should be made with that fixed then
(@orowith2os ?)

**Comment by orowith2os** [comment] 2023-01-27 18:12
If its the appendSwitches doing it, I suppose it could be reverted to the old way of doing it. It could also be the WindowDecorations flag messing it up, but I doubt that.

**Comment by orowith2os** [comment] 2023-01-27 18:13
I'm also fairly busy personally, but I will try to fix this up when I can (possibly will be a few weeks, sorry)

**Comment by ghost** [comment] 2023-01-27 18:15
> If its the appendSwitches doing it, I suppose it could be reverted to the old way of doing it. It could also be the WindowDecorations flag messing it up, but I doubt that.

hi, please take a look at https://github.com/ArmCord/ArmCord/pull/339#issuecomment-1406878837

**Comment by fxzzi** [comment] 2023-02-01 12:10
When I run in wayland it defaults to XWayland. Adding the parameter `--ozone-platform=wayland` now makes it launch in Wayland mode, but it crashes instantly with these errors in the terminal: ![](https://cdn.upload.systems/uploads/unW1lGFW.png)

**Comment by Vendicated** [comment] 2023-02-01 12:40
those permission denieds are super weird, that seems like an issue with ur system. Make sure you're in the audio and video groups 🤔 
```sh
sudo usermod -aG audio,video $USER
```

**Comment by fxzzi** [comment] 2023-02-01 13:40
@Vendicated just added myself to those groups, restarted, and tried again. However the issue is still present. This happens on all electron apps when running in a native wayland mode. I think it's just nvidia shenanigans again.

**Comment by smartfrigde** [comment] 2023-05-13 13:24
Fixed in E21 builds

**Closed as completed by smartfrigde** 2023-05-13 13:24 UTC
Labels: bug
