### ISSUE TITLE
Snap doesn't exist for arm64

### ISSUE THREAD

**Issue by ghost** [smartfrigde/armcord#567] opened 2024-04-25 16:14 UTC
**Describe the bug**
I expected to be able to install ArmCord on my arm64 openSUSE system, but it says it's only available for amd64.

**To Reproduce**
1. Run "sudo snap install armcord"
2. Error "error: snap "armcord" is not available on edge for this architecture (arm64) but exists on other architectures (amd64)."

**Expected behavior**
armcord installs and can be run.

**Desktop (please complete the following information):**
 - OS: Linux (openSUSE Tumbleweed arm64/aarch64).
 - Method of installation: snap
 - Version: 3.2.6 and 3.3.0 (stable and edge).

**Comment by irasponsible** [comment] 2024-06-24 04:14
Have you tried the aarch64 rpm package on the [releases page](https://github.com/ArmCord/ArmCord/releases/tag/v3.2.7)?  
It's not a *solution* to it being missing from the Snap store, but it should install and allow you to use Armcord.

**Comment by SomeAspy** [comment] 2024-10-15 01:49
duplicate of #415

**Closed as not planned by SomeAspy** 2024-10-15 01:49 UTC
Labels: bug
