### ISSUE TITLE
Can't set hotkeys. 

### ISSUE THREAD

**Issue by elogrus** [smartfrigde/armcord#683] opened 2024-08-15 14:26 UTC
I can't install custom hotkeys. Armcord thinks that I'm using a browser, but you can't set hotkeys in the browser version of Discord.

**Comment by smartfrigde** [comment] 2024-08-15 14:27
Duplicate of https://github.com/ArmCord/ArmCord/issues/88

**Closed as not planned by smartfrigde** 2024-08-15 14:27 UTC
Labels: bug
