### ISSUE TITLE
Closing Stream without Opening it Crashes Legcord

### ISSUE THREAD

**Issue by Tahinli** [smartfrigde/armcord#752] opened 2024-10-17 08:52 UTC
**Describe the bug**
Hi, 

If you try to open a stream in Wayland you will see windows/screen selector for stream. If you close this selector without choosing anything, it crashes Legcord

**To Reproduce**
1. Click stream button
2. Close Wayland screenshare selector without choosing anything
3. Crash

**Expected behavior**
It should not crash

**Screenshots**
left one is windows selector for Wayland
![image](https://github.com/user-attachments/assets/1e60c6b7-d9ad-40cb-9434-2a5ede86940b)

**Desktop (please complete the following information):**
 - OS: Fedora 40 | Hyprland
 - AppImage
 - Version 1.0.1

**Comment by SomeAspy** [comment] 2024-10-19 16:42
duplicate of #594

**Closed as not planned by SomeAspy** 2024-10-19 16:42 UTC
Labels: bug
