### ISSUE TITLE
Armcord gets stuck on a infinite loading screen

### ISSUE THREAD

**Issue by Git-North** [smartfrigde/armcord#538] opened 2023-12-24 09:18 UTC
**Describe the bug**
trying to open Armcord results it in getting stuck on the clyde spinning loading screen. image below

**To Reproduce**
- Try to open armcord on windows

**Expected behavior**
- For armcord to load into discord. do normal discord things

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/72702125/365f9674-4b94-44a5-8dec-b01ec240885b)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - ```winget install -e --id ArmCord.ArmCord --source winget```
 - Version [3.2.5 Potato]

**Additional context**
killing armcord.exe and re opening, waiting it and repeating it a few times usually solves the problem. tho it's very inconvinient

**Comment by Kyruf** [comment] 2023-12-25 01:03
same here, has been like this for a few days for me

**Comment by iraizo** [comment] 2024-01-04 12:31
tbh now i cant even get it to start again, its completely broken for me

**Comment by Jaoheah** [comment] 2024-01-09 17:56
This is most likely a duplicate of https://github.com/ArmCord/ArmCord/issues/513. Try the steps mentioned in the link. Find the install directory of ArmCord, then navigate to the storage folder, and then delete the window.json file.

**Closed as not planned** 2024-02-03 19:43 UTC
Labels: bug
