### ISSUE TITLE
Render frame was disposed after WebFrameMain could be accessed

### ISSUE THREAD

**Issue by haoxiangliew** [smartfrigde/armcord#343] opened 2023-02-02 07:14 UTC
**Describe the bug**
After in a voice call with screenshare for a while, or sometimes without screenshare, this error will occur.

![image](https://user-images.githubusercontent.com/62730710/216256417-b4851b94-ed68-479d-add9-8662c6bf2db3.png)

And the frame turns white, while disconnecting me from call and screensharing.

![image](https://user-images.githubusercontent.com/62730710/216256937-3e6e9b45-d676-40f5-b678-ef420216b1e4.png)

**Expected behavior**
It works fine.

**Desktop (please complete the following information):**
 - OS: NixOS Unstable
 - DE: Gnome 43.2 Wayland
 - Command: `armcord --enable-features=WaylandWindowDecorations,WebRTCPipeWireCapturer`
 - Build: from nixpkgs https://search.nixos.org with Wayland specific patches applied
 - Version: Release Armcord 3.1.4

**Comment by smartfrigde** [comment] 2023-07-26 14:32
Duplicate of #318

**Closed as not planned by smartfrigde** 2023-07-26 14:32 UTC
Labels: bug
