### ISSUE TITLE
Non-stop ram increase while in the voice chat

### ISSUE THREAD

**Issue by neul-lw** [smartfrigde/armcord#417] opened 2023-07-02 14:51 UTC
**Describe the bug**
Ram usage is increasing over time when in the voice chat.
Armcord was using 300-400mb when not in voice chat. It started to increase and reached 1.4gb memory usage when i was in the voice chat with 3 people (total 4 people).

**To Reproduce**
1. Open Armcord
2. Join to Voice Chat
3. RAM Usage increasing over time

**Expected behavior**
After joining voice chat, the ram usage shouldn't increasing over time.

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/64253023/4a2307c7-abbd-44e3-bb28-a80072e96443)

**Desktop (please complete the following information):**
 - OS: Linux,Fedora 38 Workstation
 - Method of installation: Flatpak
 - Version: ArmCord Version: 3.2.0

**Additional context**
I think ram increase might depend on how many people are in the voice chat. There was 4 people, including me in the voice chat. My System Load increased to %240, i had to close the armcord and enter voice chat from the normal discord client.

**Comment by smartfrigde** [comment] 2023-07-26 14:32
Duplicate of #318

**Closed as not planned by smartfrigde** 2023-07-26 14:32 UTC
Labels: bug
