### ISSUE TITLE
Safari Doesn't Come to Foreground When Opening Links from Legcord

### ISSUE THREAD

**Issue by EliasMET** [smartfrigde/armcord#791] opened 2024-11-24 22:13 UTC
**Describe the bug**

When I click on a link in Legcord, the link opens in Safari, but Legcord stays in the foreground instead of switching to Safari as expected.

**To Reproduce**

1. Open Legcord.
2. Click on any link.
3. Notice that Legcord remains in the foreground.

**Expected behavior**

Safari should open the link and come to the foreground, so I can view the content immediately.

**Desktop (please complete the following information):**
- **OS:** macOS 15.1.1
- **Method of installation:** .dmg
- **Version:** 1.0.2

**Comment by SomeAspy** [comment] 2024-11-24 23:18
duplicate of #784

**Closed as not planned by SomeAspy** 2024-11-24 23:18 UTC
Labels: bug
