### ISSUE TITLE
i3 missing screenshare options

### ISSUE THREAD

**Issue by maedas** [smartfrigde/armcord#566] opened 2024-04-23 14:22 UTC
**Describe the bug**
Missing options to set FPS/Resolution on i3.

**To Reproduce**
With i3 as WM:
Open Armcord
Start voicecall/join voice channel
Try sharing screen.
Option window to share screen looks like attached picture
(Changing window to floating does not resolve anything.)

**Expected behavior**
Seeing options to change resolution & fps

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/19661397/42326b42-efaa-4fb4-a05a-7d15a8f7566d)

**Desktop (please complete the following information):**
 - OS: NixOS 23.11
 - Method of installation: nixpkgs
 - Version: stable 286654 (b3db605)

**Comment by smartfrigde** [comment] 2024-05-19 10:39
Duplicate of https://github.com/ArmCord/ArmCord/issues/418

**Closed as not planned by smartfrigde** 2024-05-19 10:39 UTC
Labels: bug
