### ISSUE TITLE
[macOS] Microphone and camera permissions not requested

### ISSUE THREAD

**Issue by KaBankz** [smartfrigde/armcord#759] opened 2024-10-22 21:33 UTC
**Describe the bug**

Legcord does not request permissions for either the microphone or camera on macOS.

**To Reproduce**
1. Install Legcord on macOS
2. Try to start a call
3. Check 'System Settings > Privacy & Security > Microphone|Camera'

**Expected behavior**

Legcord should request permissions for the microphone and camera on macOS.

**Desktop (please complete the following information):**
 - OS: macOS
 - Method of installation: Homebrew
 - Version: 1.0.2

**Additional context**

I tried doing a clean install of Legcord, but no luck.

I thought this issue was fixed in https://github.com/Legcord/Legcord/commit/e60e8e9d502576c96028c4c839e5e8cbe2aa0061, but apparently not.

**Comment by 6Fv** [comment] 2024-11-01 16:19
Sharing my workaround:
```
sqlite3 ~/Library/Application\ Support/com.apple.TCC/TCC.db
insert into access values ('kTCCServiceMicrophone','app.legcord.Legcord', 0, 2, 2, 1, null, null, null, 'UNUSED', null, null, 1669648527,null,null,'UNUSED',1669648527);
```

Source:
https://superuser.com/a/1755116

**Comment by SomeAspy** [comment] 2024-11-03 21:37
Replicated this issue, if legcord is launched from the CLI, it will work however. I'll have to take another look at this

**Comment by SomeAspy** [comment] 2024-11-03 22:03
I've just pushed this to the dev branch after testing on my own macbook. Things should be all good now!

**Comment by billyjacoby** [comment] 2024-11-08 17:25
Is there anyway for me to fix this on the current build? I can't compile locally as I don't have a provisioning profile and the above sqlite3 command does not work for me

**Comment by ghost** [comment] 2024-11-10 01:33
The workaround worked for me, thank you!

**Comment by SomeAspy** [comment] 2024-11-10 02:50
> Is there anyway for me to fix this on the current build? I can't compile locally as I don't have a provisioning profile and the above sqlite3 command does not work for me

Hi, we will push this into stable soon

**Comment by IAmVisco** [comment] 2024-11-12 19:28
I'm not sure this is fixed. I pulled the latest rolling build (1.0.3-2fbdf5c), but the pop-up is still not there. I installed it on top of my existing stable 1.0.2 (like most old users would) and the only thing that changed is that Discord now knows that it has no permissions 
<img width="712" alt="image" src="https://github.com/user-attachments/assets/6494ebe8-ef32-48ea-8f09-d58f9531d265">
The button leads to the [Chrome (browser) permissions guide](https://support.discord.com/hc/en-us/articles/205093487-How-do-I-enable-my-mic-in-Chrome).

**Comment by SomeAspy** [comment] 2024-11-12 19:42
I just made a new release, can you try that?

**Comment by IAmVisco** [comment] 2024-11-12 19:43
Sure give me a minute

**Comment by IAmVisco** [comment] 2024-11-12 19:52
@SomeAspy Nope, still the same on stable 1.0.3. Attaching a video too.

https://github.com/user-attachments/assets/3bdfec40-8276-4935-8ebf-02763d634a41

**Comment by SomeAspy** [comment] 2024-11-12 20:22
can you send the contents of your config file?

**Comment by IAmVisco** [comment] 2024-11-12 20:27
<details>
<summary>There you go</summary>

**OS:** darwin Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000
**Architecture:** arm64
**Legcord version:** 1.0.3
**Electron version:** 32.2.2
```json
{
    "windowStyle": "default",
    "channel": "stable",
    "legcordCSP": true,
    "minimizeToTray": true,
    "keybinds": [],
    "audio": "loopbackWithMute",
    "multiInstance": false,
    "mods": [
        "vencord"
    ],
    "transparency": "none",
    "spellcheck": true,
    "hardwareAcceleration": true,
    "performanceMode": "battery",
    "skipSplash": false,
    "inviteWebsocket": true,
    "startMinimized": false,
    "tray": false,
    "disableHttpCache": false,
    "customJsBundle": "https://legcord.app/placeholder.js",
    "customCssBundle": "https://legcord.app/placeholder.css",
    "disableAutogain": false,
    "useLegacyCapturer": false,
    "mobileMode": false,
    "trayIcon": "dynamic",
    "doneSetup": true,
    "clientName": "Legcord",
    "customIcon": "/Applications/legcord.app/Contents/Resources/app.asar/assets/desktop.png",
    "smoothScroll": true,
    "autoScroll": false,
    "modCache": {
        "shelter": "c6fb071f74089639a7b2b6177144d31192cbf916",
        "vencord": "7ef536c6c68f60ac94e89f37968ef83ef3d4b35a"
    }
}
```

</details>

**Comment by billyjacoby** [comment] 2024-11-12 20:38
Just chiming in here since i saw the activity - i'm seeing the same issue still on the latest version. 

I'm happy to jump on a call to help get this figured out, i unfortunately can't use this until the mic issue is resolved

**Comment by SomeAspy** [comment] 2024-11-12 21:34
Strange. Everytime the window requests permissions, this should be passed to MacOS.
https://github.com/Legcord/Legcord/commit/75123e51af0dd14d368178c1d4f1174a689a2f57#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR113

**Comment by IAmVisco** [comment] 2024-11-12 21:36
[Checking the docs](https://www.electronjs.org/docs/latest/api/system-preferences#systempreferencesaskformediaaccessmediatype-macos), the method returns a Promise, maybe you need to await it?

**Comment by SomeAspy** [comment] 2024-11-12 21:38
I fixed that here, https://github.com/Legcord/Legcord/commit/111ce26ecaf0d9c1650a8c12b7f06ed258c7912f#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR128

if Discord is detecting that permissions are rejected, then the if statement that rejects the callback is firing

**Comment by IAmVisco** [comment] 2024-11-12 21:42
Check the `Important` note below in [the docs](https://www.electronjs.org/docs/latest/api/system-preferences#systempreferencesaskformediaaccessmediatype-macos). I don't see any .plist in the repo and not sure how Electron handles those. Can it be the issue?

**Comment by SomeAspy** [comment] 2024-11-12 21:43
Electron builder handles generating the plists, from what I understand. I know it works, because on my own mac I tested on I got the permission request.

I do not have time (right now) to dive into this, but rest assured I will soon.

**Comment by IAmVisco** [comment] 2024-11-12 21:44
Then I'm flat out of suggestions. I'm on macOS 15.1 so the sqlite hack doesn't work anymore. I appreciate your efforts and will just wait patiently for the fix. Thanks!

**Comment by ymatuhin** [comment] 2024-11-12 22:11
I've just downloaded Version 1.0.3 (1.0.3) for the very first time and same no permission requested.

**Comment by billyjacoby** [comment] 2024-11-13 00:28
Okay I'm running locally now and gonna try to dig in more here - initial thing I'm noticing is that when running in dev mode the terminal (Warp) is what's asking for mic & camera permissions - not Legcord.

edit: Okay I can confirm that I get the prompts if running the locally build:dev version

**Comment by ghost** [comment] 2024-11-13 12:42
@IAmVisco That's really weird that the sqlite workaround didn't work; I'm on 15.1 (when I ran it) and it worked fine for me, so perhaps a security program is blocking it or-?

**Comment by IAmVisco** [comment] 2024-11-13 12:45
Not sure... It was saying something about authorization denied (even with sudo), and Google told me I needed to update ownership of the DB which is potentially breaking so I didn't touch it further. I don't have any special software (it's not a company laptop), so not sure why it wouldn't work.

**Comment by ghost** [comment] 2024-11-13 12:54
(NOT security best practice)

But what I did was that I entered `sudo -i`
found the path of sqlite 

and then pasted the command in which worked

**Comment by ghost** [comment] 2024-11-14 03:39
@BlueSkiesLife no clue what you did exactly but its not working on my machine (M1 Pro on 15.2), can you share the exact commands you ran?

**Comment by ghost** [comment] 2024-11-14 05:56
@toffee-makes-things  @IAmVisco 

(make sure you're NOT in sudo, i don't know how i missed that. sorry for the incorrect instructions! I was just really tired when I responded

make sure that terminal has full disk access in system settings.

`tccutil reset Microphone`
\<press enter>
`sqlite3 '/Users/<myusername>/Library/Application Support/com.apple.TCC/TCC.db'`
\<press enter>
`insert into access values ('kTCCServiceMicrophone','app.legcord.Legcord', 0, 2, 2, 1, null, null, null, 'UNUSED', null, null, 1669648527); `
\<press enter>
`.quit`
\<close terminal>

if there's no errors, it should work. (restart your system settings after doing this and it should show up)


sources:

https://www.reluctant-tech-traveler.net/prod/user/showblog/macos-adding-apps-to-camera-mic-access-1
https://superuser.com/questions/1441270/apps-dont-show-up-in-camera-and-microphone-privacy-settings-in-macbook/1755116#1755116

**Comment by tiimonn** [comment] 2024-11-14 17:16
> @toffee-makes-things @IAmVisco
> 
> (make sure you're NOT in sudo, i don't know how i missed that. sorry for the incorrect instructions! I was just really tired when I responded
> 
> make sure that terminal has full disk access in system settings.
> 
> `tccutil reset Microphone` <press enter> `sqlite3 '/Users/<myusername>/Library/Application Support/com.apple.TCC/TCC.db'` <press enter> `insert into access values ('kTCCServiceMicrophone','app.legcord.Legcord', 0, 2, 2, 1, null, null, null, 'UNUSED', null, null, 1669648527); ` <press enter> `.quit` <close terminal>
> 
> if there's no errors, it should work. (restart your system settings after doing this and it should show up)
> 
> sources:
> 
> https://www.reluctant-tech-traveler.net/prod/user/showblog/macos-adding-apps-to-camera-mic-access-1 https://superuser.com/questions/1441270/apps-dont-show-up-in-camera-and-microphone-privacy-settings-in-macbook/1755116#1755116

That should only be the temporary solution, right?

**Comment by ghost** [comment] 2024-11-15 01:54
@tiimonn 
Ideally, this would not even be needed (ideally the app would request permissions properly). 
So yes, it is only a temporary solution.

**Comment by marcohefti** [comment] 2024-11-16 12:07
Newest update broke the permissions fix me. 

Vencord never requested permissions but it used to work with the manual sqlite insert workaround. 

Since the update it doesn't anymore even though I can see in Privacy & Security -> Microphone that Legcord still has permissions. 

Tried many time to reset permissions, manually re-add it with the sqlite inserts and system restarts but doesn't work anymore.

![Screenshot 2024-11-16 at 19 08 43](https://github.com/user-attachments/assets/357392c4-7738-4496-9444-0878319b971d)

**Comment by SomeAspy** [comment] 2024-11-16 16:12
so basically, this is the code
```ts
            if (permission === "media") {
                if (process.platform === "darwin") {
                    const mic = await systemPreferences.askForMediaAccess("microphone");
                    const cam = await systemPreferences.askForMediaAccess("camera");
                    if (!(mic && cam)) {
                        callback(false);
                    }
                } else {
                    callback(true);
                }
            }
```
Since discord is detecting it is not approved, the false callback is being fired.

**Comment by SomeAspy** [comment] 2024-11-16 16:40
Hi all, I just rewrote the logic for permissions on mac, and it seems to be working for me.
give it a try, its on the dev branch now.
```ts
            if (permission === "media") {
                if (process.platform === "darwin") {
                    callback(
                        await new Promise<boolean>((resolve, reject) => {
                            systemPreferences.askForMediaAccess("microphone").then((isGranted) => {
                                if (!isGranted) {
                                    reject("Microphone permission rejected");
                                    return;
                                }
                            });
                            systemPreferences.askForMediaAccess("camera").then((isGranted) => {
                                if (!isGranted) {
                                    reject("Camera permission rejected");
                                    return;
                                }
                            });
                            resolve(true);
                        }),
                    );
                }
            }
```

**Comment by IAmVisco** [comment] 2024-11-16 19:15
Just checked the latest build (6947982), sadly the issue persists for me
<img width="756" alt="image" src="https://github.com/user-attachments/assets/cfffde6a-94d1-48ea-943c-21293fc86027">

**Comment by SomeAspy** [comment] 2024-11-16 20:24
Can you try uninstalling legcord and deleting `~/Library/Application\ Support/legcord`
Then try reinstalling.
The only thing I can think of is electron caching the prior failure for whatever reason.
also double check you have granted the permissions in Privacy and Security of your Mac settings

I don't really know otherwise.

**Comment by IAmVisco** [comment] 2024-11-16 20:57
Still no pop-up on a clean install. I gave up and did a deeper dive into the sqlite3 hack and turns out I just needed to give full disk access to iTerm2 for it to work. For future comers, if sqlite insert says it has 17 columns and not 13, use [this](https://github.com/Legcord/Legcord/issues/759#issuecomment-2452160107) command instead of BlueSkiesLife's one.

**Comment by SomeAspy** [comment] 2024-11-16 23:35
I just pushed some debug logging on the latest dev build, can you check it out? 
![image](https://github.com/user-attachments/assets/62ce53c6-6348-4541-bfb1-b3ebfdbe6603)
(I fixed it saying screen)

**Comment by IAmVisco** [comment] 2024-11-16 23:56
We probably should've started with logs. 
<img width="1008" alt="image" src="https://github.com/user-attachments/assets/5bc9f2c3-4dd7-4d45-a75e-5d9b703b5285">
I get this right now and trying to get your logs to show up, but they don't appear in any console.
The error on the image might be related to the Discord video filters, it gets thrown in that code area.

Lower error though gets thrown here 
<img width="368" alt="image" src="https://github.com/user-attachments/assets/3ac50cb9-07b5-42fd-8eaf-933d233ad8d0">

**Comment by SomeAspy** [comment] 2024-11-16 23:58
@IAmVisco they will appear in the log of the actual application, ex, by running via the `legcord` command.

**Comment by SomeAspy** [comment] 2024-11-17 00:02
related: https://github.com/Vencord/Vesktop/issues/440

**Comment by IAmVisco** [comment] 2024-11-17 00:08
> @IAmVisco they will appear in the log of the actual application, ex, by running via the `legcord` command.

I installed them as dmgs, `legcord` does nothing for me and MacOS Console app has nothing of value (and no logs from above).

**Comment by SomeAspy** [comment] 2024-11-17 00:10
You should be able to navigate to Applications/legcord or wherever it is and run it directly.

**Comment by IAmVisco** [comment] 2024-11-17 00:10
Yeah but then it won't tail logs, I've tried that

edit
nvm found it

**Comment by IAmVisco** [comment] 2024-11-17 00:12
<img width="982" alt="image" src="https://github.com/user-attachments/assets/00c612ba-b9c5-42bd-98bd-65eb427e583b">
Got the pop-up on my terminal

**Comment by IAmVisco** [comment] 2024-11-17 00:14
I didn't get your logs but I got this 
![image](https://github.com/user-attachments/assets/35627f33-3bad-4f32-aedb-84bf908885fe)
<img width="383" alt="image" src="https://github.com/user-attachments/assets/0f8e0661-f383-4ab7-99be-0892c2d18357">

**Comment by IAmVisco** [comment] 2024-11-17 00:18
Yeah so I just don't get those logs, I tried clean start (with setup), resetting tcc, opening and closing settings. It would just ask the perms for iTerm, not legcord

**Comment by SomeAspy** [comment] 2024-11-17 15:46
the cache was removed, yet you have a cache hit - are you running the latest dev build? https://github.com/Legcord/Legcord/releases/tag/devbuild

**Comment by IAmVisco** [comment] 2024-11-17 15:50
I installed d21d15f22661f692967ab29118e69d3bdc2c49c8 build yesterday. I tested different configs so those two screenshots might be out of sync

**Comment by SomeAspy** [comment] 2024-11-17 15:51
when running in iterm, iterm will take ownership of the process, for the record, which is why it instead will request as iterm. I'm not sure if its the same case for the system terminal, I didn't think to check.
the build you are removing should have caching capabilities removed, yet both show a cache hit

**Comment by IAmVisco** [comment] 2024-11-17 15:57
It is 
<img width="360" alt="image" src="https://github.com/user-attachments/assets/d5c9cd23-b3f6-4e4f-8019-4e1195af67dc">

**Comment by smartfrigde** [comment] 2024-11-21 20:02
Could you try the [latest devbuild?](https://github.com/Legcord/Legcord/actions/runs/11960369685/artifacts/2220887060) (you need to download this artifact from the action run page, cause the initial CI build failed)

I think I fixed this with https://github.com/Legcord/Legcord/commit/bb983a6e1abbca80a7c82308014d85b4c8d2da08

Running macOS Monterey

**Comment by KaBankz** [comment] 2024-11-21 20:45
Just tested that build, and microphone and camera permissions are working now! 🎉

On a side note, the new icon could use some work, a purple plug on a purple gradient background does not have enough contrast imo.

**Closed as completed** 2024-11-21 20:48 UTC
Labels: bug, help wanted, screenshare or VC, MacOS

**Comment by IAmVisco** [comment] 2024-11-21 20:56
Works for me too! Thanks lads!

**Comment by wvvb** [comment] 2024-11-23 17:25
> <img alt="image" width="982" src="https://private-user-images.githubusercontent.com/18630605/386893125-00c612ba-b9c5-42bd-98bd-65eb427e583b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzODI5MzgsIm5iZiI6MTczMjM4MjYzOCwicGF0aCI6Ii8xODYzMDYwNS8zODY4OTMxMjUtMDBjNjEyYmEtYjljNS00MmJkLTk4YmQtNjVlYjQyN2U1ODNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDE3MjM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjOTUzMmI3Yjc0ZGM3N2RiYTRkZWY2ZjJlM2FmZDQyZDc2OGQ4MmU0Mzg5MDVjMTJkYTk2MmU2ODQwZDkxYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.plTFZjKJbgeOSzPWdknx-tIZ3zSEutsx1W9x1sH1wk8"> Got the pop-up on my terminal

sorry to ask but what terminal is this?

**Comment by SomeAspy** [comment] 2024-11-23 17:26
@ryzmae https://iterm2.com/

**Comment by IAmVisco** [comment] 2024-11-23 17:27
> sorry to ask but what terminal is this?

That just iTerm2 with the default dark theme/style

**Comment by wvvb** [comment] 2024-11-23 18:18
> > sorry to ask but what terminal is this?
> 
> That just iTerm2 with the default dark theme/style


could you share you config please mine doesnt look like this

**Comment by SomeAspy** [comment] 2024-11-23 18:26
Hi, to further discuss terminal config, please do so in the discord server. https://discord.gg/ShDNSTj2

**Comment by IAmVisco** [comment] 2024-11-23 18:26
@ryzmae It was actually called "Minimal" 
<img width="897" alt="image" src="https://github.com/user-attachments/assets/b9ccb4c6-3b31-49b0-9b88-ee63a44af610">
Here's the profile config https://gist.github.com/IAmVisco/6b7ccaf4df20391c08a8666675120926
It uses Monokai Remastered colors in case it won't have the name
