### ISSUE TITLE
ArmCord does not support Arm64 architectures

### ISSUE THREAD

**Issue by drujensen** [smartfrigde/armcord#465] opened 2023-09-14 17:02 UTC
**Is your feature request related to a problem? Please describe.**

I found your project by searching for `Discord for Arm64 Linux`.  It would be great if this application supported that architecture.

**Describe the solution you'd like**

The ability to install on a Linux Arm64 system.
```
sudo snap install armcord --channel=latest/edge
[sudo] password for drujensen: 
error: snap "armcord" is not available on edge for this architecture (arm64) but exists on other
       architectures (amd64).
```

**Describe alternatives you've considered**

N/A

**Additional context**

The name implies support for Arm but it doesn't.

**Comment by smartfrigde** [comment] 2023-09-14 17:07
ArmCord actually supports ARM64 obviously however building ARM snaps require an ARM machine. Please use Flatpak/Deb/any other package for the time being. Duplicate of https://github.com/ArmCord/ArmCord/issues/415

**Closed as not planned by smartfrigde** 2023-09-14 17:07 UTC
