### ISSUE TITLE
Armcord not being able to get mods

### ISSUE THREAD

**Issue by pipigguts** [smartfrigde/armcord#272] opened 2022-11-28 15:28 UTC
**Describe the bug**
I updated Armcord from 3.0.8 to 3.1.0 and i was expecting the ability to select the mod client i want to use but it gave me an error, i tried uninstalling and reinstalling but the same thing again. I can still use armcord, just without any mod clients(like vencord and so on), I'm also on windows 11 if you wondered.

**To Reproduce**
1. Install Armcord
2. Double click to turn it on
3. See error

**Expected behavior**
I expected to see a menu to select the mod client i wanna use just like it did before when goosemod and cumcord was a thing

**Screenshots**
![image](https://user-images.githubusercontent.com/107474743/204314447-59423632-b33c-440b-8395-0d840920c4e3.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Method of installation: setup exe
 - Version: 3.1.0

**Additional context**
I dont know how to use github that well so if that image didnt upload, i got it on imgur too
https://imgur.com/a/IK3aTlM

**Comment by smartfrigde** [comment] 2022-11-28 16:30
Can you run armcord from cmd/powershell or similar and share the logs?

For example from powershell
`.\ArmCord.exe`

**Comment by pipigguts** [comment] 2022-11-29 07:10
1.
![image](https://user-images.githubusercontent.com/107474743/204461756-a3ef5f32-6c84-481c-97d5-0276c3eac32d.png)
https://imgur.com/a/Q3WrVZX
2.
![image](https://user-images.githubusercontent.com/107474743/204462211-bbccdf83-a101-441b-aef5-c3263b994dcf.png)
https://imgur.com/a/cwfyzvS

I couldn't figure out how to run the armcord with that, so I instead used the "open in terminal" option on the desktop and opened the shortcut, I hope that's not a big deal.

**Comment by smartfrigde** [comment] 2022-11-29 13:15
I see the issue, go to settings and change the mod value to Vencord for example as it's still set to Flicker which is dead. If you can't access settings for some reason you can do this manually.
Go to `%	appdata%\ArmCord\storage` and modify `settings.json`. You need to change the mods value to either `vencord` or `shelter`.
For example with Vencord it should look like this
```json
{
"mods": "vencord",
}
```

Obviously mods value isn't the only one there, so don't overwrite it with this example but just change that one particular key.
If you need any more help feel free to comment on this issue as I'll close it. It's not a bug, it's more issue of ArmCord not handling updating settings over versions really well.

**Comment by pipigguts** [comment] 2022-11-30 15:23
thank you, it worked but... i dont have any titlebar anymore

**Comment by Avezamal** [comment] 2022-12-02 18:37
Win 10, Mine was set to shelter, i changed it to vencord and that worked, but the titlebar did disappear, still less annoying than the error message.

**Comment by smartfrigde** [comment] 2022-12-03 12:05
If your experiencing issues with titlebar not appearing on 3.1.0 enable `Automatic patches` in settings. It'll inject a quick fix for it, while you're waiting for next release. Also due to a typo, when you load up settings the setting will always show that's it's disabled.
Source code of the fix: https://github.com/ArmCord/Patches/blob/main/3.1.0/patch.js

If you have any more issues ask me on our Discord https://discord.gg/TnhxcqynZ2

**Closed as completed** 2022-12-06 07:35 UTC
Labels: bug
