### ISSUE TITLE
Are there any plans to implement screenshare audio?

### ISSUE THREAD

**Issue by sasspaper** [smartfrigde/armcord#498] opened 2023-10-30 05:04 UTC
**Is your feature request related to a problem? Please describe.**
No audio during screensharing

**Describe the solution you'd like**
[Vesktop](https://github.com/edisionnano/Screenshare-with-audio-on-Discord-with-Linux) has already found a solution to this besides the discordscreen-audio app

**Describe alternatives you've considered**
Crying

**Comment by smartfrigde** [comment] 2024-01-28 18:34
Duplicate of https://github.com/ArmCord/ArmCord/issues/435

**Closed as not planned by smartfrigde** 2024-01-28 18:34 UTC
